volumes:
  db-data:
networks:
  instavote:
    driver: bridge
services:
  vote:
    build: 
      context: ./vote
    # image: okapetanios/vote:latest
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote
  redis:
    image: redis:alpine
    networks:
      - instavote
      
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - instavote

    # image: postgres:9.4
    # volumes:
    #   - "db-data:/var/lib/postgresql/data"
    # networks:
    #   - instavote
    # environment: 
    #   - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    # image: okapetanios/result:latest
    build:
      context: ./result
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - instavote
  worker:
    # image: okapetanios/worker:latest
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
